# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
- wenxin-test

pool: docker-agent

variables:
  PYTHON: 'python3.8'
  IMAGE_NAME: 'neural-compressor'
  IMAGE_TAG: 'py38'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Clean
    steps:
    - script: sudo rm -fr $(Agent.BuildDirectory) || true
    #workspace:
    #  clean: all
  
  - job: Build
    displayName: Build
    steps:
    - script: |
        docker stop $(docker ps -aq)
        docker rm -vf $(docker ps -aq) || true
      displayName: 'Clean Docker'

    - checkout: self
      clean: true  

    - script: |
        pwd
        ls -l
        docker run --rm -v /home/azureuser-inc/myagent/workspace/1/s:/neural_compressor ${IMAGE_NAME}:${IMAGE_TAG} /bin/bash +x -c "cd /neural_compressor && python -m pip install --no-cache-dir -r requirements.txt && pip install intel-tensorflow && python setup.py sdist bdist_wheel && pip install dist/neural_compressor-1.13-py3-none-any.whl && pip list && python test/strategy/test_bayesian.py"
      displayName: 'find repo'

    - script: |
        docker images | grep -i neural-compressor
        docker ps
      displayName: 'Check docker'
    
    - script: |
        sudo rm -fr /home/azureuser-inc/myagent/workspace/1/s/*
      displayName: 'clean up'
