# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr:
- wenxin-test

pool: docker-agent

variables:
  IMAGE_NAME: 'neural-compressor'
  IMAGE_TAG: 'py38'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - script: |
        echo ${BUILD_SOURCESDIRECTORY}
        sudo rm -fr ${BUILD_SOURCESDIRECTORY} || true
      displayName: 'Clean workspace'
    
    - checkout: self
      displayName: "Checkout out Repo"
    
    - script: |
        if [[ ! $(docker images | grep -i neural-compressor) ]]; then
            docker build -f ${BUILD_SOURCESDIRECTORY}/.azure-pipelines/docker/Dockerfile.devel -t ${IMAGE_NAME}:${IMAGE_TAG} .
        fi
        docker images | grep -i neural-compressor
        [[ $? -ne 0 ]] && exit 1
      displayName: "Build Devel Images"

    - script: |
        docker stop $(docker ps -aq)
        docker rm -vf $(docker ps -aq) || true
      displayName: 'Clean Docker'

    - script: |
        docker run --disable-content-trust --privileged --name="pr" --hostname="pr-host" -v ${BUILD_SOURCESDIRECTORY}:/neural_compressor  ${IMAGE_NAME}:${IMAGE_TAG} /bin/bash +x -c "cd /neural_compressor && python -m pip install --no-cache-dir -r requirements.txt && python setup.py sdist bdist_wheel && pip install dist/neural_compressor-*.whl && pip list  && python test/strategy/test_bayesian.py"
      displayName: 'Build Binary and Run UT'


