trigger:
  - code-scan
pr: none
pool: suyue-test

variables:
  IMAGE_NAME: "code-scan"
  IMAGE_TAG: "1.0"
  CODE_SCAN_PATH: ".azure-pipelines/scripts/codeScan"
  CODE_SCAN_LOG_PATH: "scanLog"
  TARGET_PATH: "/neural_compressor"
  BANDIT_CONTAINER_NAME: "bandit"
  PYLINT_CONTAINER_NAME: "pylint"
  PYSPELLING_CONTAINER_NAME: "pyspelling"
  COPYRIGHT_CONTAINER_NAME: "copyright"

  TARGET_BRANCH: $(System.PullRequest.TargetBranch)
  CURRENT_PATH: $(Build.SourcesDirectory)

stages:
  - stage: BanditCodeScan
    displayName: Bandit Code Scan
    dependsOn: []
    jobs:
      - job: Bandit
        displayName: Bandit
        steps:
          - script: |
              echo ${BUILD_SOURCESDIRECTORY}
              sudo rm -fr ${BUILD_SOURCESDIRECTORY} || true
              echo y | docker system prune
            displayName: "Clean workspace"
          - checkout: self
            displayName: "Checkout out Repo"
          - script: |
              if [[ ! $(docker images | grep -i ${IMAGE_NAME}) ]]; then
                  docker build -f ${BUILD_SOURCESDIRECTORY}/.azure-pipelines/docker/Dockerfile.devel -t ${IMAGE_NAME}:${IMAGE_TAG} .
              fi
              docker images | grep -i ${IMAGE_NAME}
              if [[ $? -ne 0 ]]; then
                echo "NO Such Image ${IMAGE_NAME}"
                exit 1
              fi
            displayName: "Build Devel Images"
          - script: |
              docker stop $(docker ps -aq)
              docker rm -vf $(docker ps -aq) || true
            displayName: "Clean Docker"

          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                docker run --disable-content-trust --privileged --name=$(BANDIT_CONTAINER_NAME) -v ${BUILD_SOURCESDIRECTORY}:$(TARGET_PATH) ${IMAGE_NAME}:${IMAGE_TAG} /bin/bash  +x -c "cd $(TARGET_PATH) && bash $(TARGET_PATH)/$(CODE_SCAN_PATH)/$(BANDIT_CONTAINER_NAME)/bandit.sh  --TARGET_PATH $(TARGET_PATH)"
                docker cp $(BANDIT_CONTAINER_NAME):/lpot-bandit.log $(CURRENT_PATH)/$(CODE_SCAN_PATH)/$(CODE_SCAN_LOG_PATH)/lpot-bandit.log

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: $(CURRENT_PATH)/$(CODE_SCAN_PATH)/$(CODE_SCAN_LOG_PATH)/lpot-bandit.log
              artifact: $(BANDIT_CONTAINER_NAME)
              publishLocation: "pipeline"

  - stage: PylintCodeScan
    displayName: Pylint Code Scan
    dependsOn: []
    jobs:
      - job: Pylint
        displayName: Pylint
        steps:
          - script: |
              echo ${BUILD_SOURCESDIRECTORY}
              sudo rm -fr ${BUILD_SOURCESDIRECTORY} || true
              echo y | docker system prune
            displayName: "Clean workspace"
          - checkout: self
            displayName: "Checkout out Repo"
          - script: |
              if [[ ! $(docker images | grep -i ${IMAGE_NAME}) ]]; then
                  docker build -f ${BUILD_SOURCESDIRECTORY}/.azure-pipelines/docker/Dockerfile.devel -t ${IMAGE_NAME}:${IMAGE_TAG} .
              fi
              docker images | grep -i ${IMAGE_NAME}
              if [[ $? -ne 0 ]]; then
                echo "NO Such Image ${IMAGE_NAME}"
                exit 1
              fi
            displayName: "Build Devel Images"
          - script: |
              docker stop $(docker ps -aq)
              docker rm -vf $(docker ps -aq) || true
            displayName: "Clean Docker"

          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                docker run --disable-content-trust --privileged --name=$(PYLINT_CONTAINER_NAME) -v ${BUILD_SOURCESDIRECTORY}:$(TARGET_PATH) ${IMAGE_NAME}:${IMAGE_TAG} /bin/bash  +x -c "cd $(TARGET_PATH) && bash $(TARGET_PATH)/$(CODE_SCAN_PATH)/$(PYLINT_CONTAINER_NAME)/pylint.sh  --TARGET_PATH $(TARGET_PATH)"
                docker cp $(PYLINT_CONTAINER_NAME):/lpot-pylint.json $(CURRENT_PATH)/$(CODE_SCAN_PATH)/$(CODE_SCAN_LOG_PATH)/lpot-pylint.json

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: $(CURRENT_PATH)/$(CODE_SCAN_PATH)/$(CODE_SCAN_LOG_PATH)/lpot-pylint.json
              artifact: $(PYLINT_CONTAINER_NAME)
              publishLocation: "pipeline"

  - stage: PyspellingCodeScan
    displayName: Pyspelling Code Scan
    dependsOn: []
    jobs:
      - job: Pyspelling
        displayName: Pyspelling
        steps:
          - script: |
              echo ${BUILD_SOURCESDIRECTORY}
              sudo rm -fr ${BUILD_SOURCESDIRECTORY} || true
              echo y | docker system prune
            displayName: "Clean workspace"
          - checkout: self
            displayName: "Checkout out Repo"
          - script: |
              if [[ ! $(docker images | grep -i ${IMAGE_NAME}) ]]; then
                  docker build -f ${BUILD_SOURCESDIRECTORY}/.azure-pipelines/docker/Dockerfile.devel -t ${IMAGE_NAME}:${IMAGE_TAG} .
              fi
              docker images | grep -i ${IMAGE_NAME}
              if [[ $? -ne 0 ]]; then
                echo "NO Such Image ${IMAGE_NAME}"
                exit 1
              fi
            displayName: "Build Devel Images"
          - script: |
              docker stop $(docker ps -aq)
              docker rm -vf $(docker ps -aq) || true
            displayName: "Clean Docker"

          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                docker run --disable-content-trust --privileged --name=$(PYSPELLING_CONTAINER_NAME) -v ${BUILD_SOURCESDIRECTORY}:$(TARGET_PATH) ${IMAGE_NAME}:${IMAGE_TAG} /bin/bash  +x -c "cd $(TARGET_PATH) && bash $(TARGET_PATH)/$(CODE_SCAN_PATH)/$(PYSPELLING_CONTAINER_NAME)/pyspelling.sh  --TARGET_PATH $(TARGET_PATH)/$(CODE_SCAN_PATH) --PYSPELLING_CONTAINER_NAME $(PYSPELLING_CONTAINER_NAME)"
                docker cp $(PYSPELLING_CONTAINER_NAME):/lpot_pyspelling.log $(CURRENT_PATH)/$(CODE_SCAN_PATH)/$(CODE_SCAN_LOG_PATH)/lpot_pyspelling.log

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: $(CURRENT_PATH)/$(CODE_SCAN_PATH)/$(CODE_SCAN_LOG_PATH)/lpot_pyspelling.log
              artifact: $(PYSPELLING_CONTAINER_NAME)
              publishLocation: "pipeline"              

  # - stage: pyspelling
  #   displayName: pyspelling code scan
  #   dependsOn: []
  #   jobs:
  #   - job: Build
  #     displayName: Build
  #     steps:
  #     - script: |
  #         echo ${BUILD_SOURCESDIRECTORY}
  #         sudo rm -fr ${BUILD_SOURCESDIRECTORY} || true
  #         # echo y | docker system prune
  #       displayName: 'Clean workspace'

  #     - checkout: self
  #       displayName: "Checkout out Repo"

  #     - script: |
  #         if [[ ! $(docker images | grep -i ${IMAGE_NAME}) ]]; then
  #             docker build -f ${BUILD_SOURCESDIRECTORY}/.azure-pipelines/docker/Dockerfile.devel -t ${IMAGE_NAME}:${IMAGE_TAG} .
  #         fi
  #         docker images | grep -i ${IMAGE_NAME}
  #         if [[ $? -ne 0 ]]; then
  #           echo "NO Such Image ${IMAGE_NAME}"
  #           exit 1
  #         fi
  #       displayName: "Build Devel Images"

  #     - script: |
  #         docker stop $(docker ps -aq)
  #         docker rm -vf $(docker ps -aq) || true
  #       displayName: 'Clean Docker'

  #     - script: |
  #          docker run --disable-content-trust --privileged --name="pyspelling" --hostname="pyspelling-host" -v ${BUILD_SOURCESDIRECTORY}:/neural_compressor  ${IMAGE_NAME}:${IMAGE_TAG} /bin/bash -x -c "cd /neural_compressor && bash $(VAL_PATH)/pyspelling/pyspelling.sh  $(VAL_PATH) $(CURRENT_PATH)"
  #       displayName: 'pyspelling code scan'

  # - stage: copyright
  #   displayName: copyright code scan
  #   dependsOn: []
  #   jobs:
  #   - job: Build
  #     displayName: Build
  #     steps:
  #     - script: |
  #         echo ${BUILD_SOURCESDIRECTORY}
  #         sudo rm -fr ${BUILD_SOURCESDIRECTORY} || true
  #         # echo y | docker system prune
  #       displayName: 'Clean workspace'

  #     - checkout: self
  #       displayName: "Checkout out Repo"

  #     - script: |
  #         if [[ ! $(docker images | grep -i ${IMAGE_NAME}) ]]; then
  #             docker build -f ${BUILD_SOURCESDIRECTORY}/.azure-pipelines/docker/Dockerfile.devel -t ${IMAGE_NAME}:${IMAGE_TAG} .
  #         fi
  #         docker images | grep -i ${IMAGE_NAME}
  #         if [[ $? -ne 0 ]]; then
  #           echo "NO Such Image ${IMAGE_NAME}"
  #           exit 1
  #         fi
  #       displayName: "Build Devel Images"

  #     - script: |
  #         docker stop $(docker ps -aq)
  #         docker rm -vf $(docker ps -aq) || true
  #       displayName: 'Clean Docker'

  #     - script: |
  #         docker run --env PYTHONPATH="/neural-compressor" ${IMAGE_NAME}:${IMAGE_TAG}  /bin/bash +x  -c "pwd && bash $(VAL_PATH)/copyright/copy_right.sh  $(target_path) $(TARGET_BRANCH) $(VAL_PATH)"
  #         # docker run --disable-content-trust --privileged --name="copyright" --hostname="copyright-host" -v ${BUILD_SOURCESDIRECTORY}:/neural_compressor  ${IMAGE_NAME}:${IMAGE_TAG} /bin/bash  +x -c "cd /neural_compressor && bash $(VAL_PATH)/copyright/copy_right.sh  $(target_path)   $(TARGET_BRANCH)  $(VAL_PATH)"
  #       displayName: 'copyright code scan'
