trigger: none

pr:
  branches:
    include:
    - master
  path:
    include:
    - neural_compressor.ux

pool: suyue-test

variables:
  IMAGE_NAME: 'neural-compressor'
  IMAGE_TAG: 'py38'

stages:
- stage:
  displayName: Unit Test for UX
  jobs:
  - job:
    steps:
    - script: |
        echo ${BUILD_SOURCESDIRECTORY}
        sudo rm -fr ${BUILD_SOURCESDIRECTORY} || true
      displayName: 'Clean workspace'

    - checkout: self
      displayName: "Checkout out Repo"

    - script: |
        # for test
        docker image rm ${IMAGE_NAME}:${IMAGE_TAG}
        if [[ ! $(docker images | grep -i '${IMAGE_NAME}:${IMAGE_TAG}' ) ]]; then
            docker build -f ${BUILD_SOURCESDIRECTORY}/.azure-pipelines/docker/Dockerfile.devel -t ${IMAGE_NAME}:${IMAGE_TAG} .
        fi
        docker images | grep -i ${IMAGE_NAME}
        if [[ $? -ne 0 ]]; then
          echo "NO Such Image ${IMAGE_NAME}"
          exit 1
        fi
      displayName: "Build develop docker image"

    - script: |
        docker stop $(docker ps -aq)
        docker rm -vf $(docker ps -aq) || true
        env | sort
      displayName: 'Clean docker'

    - script: |
        docker run --disable-content-trust --privileged --name="pr" --hostname="pr-host" -v ${BUILD_SOURCESDIRECTORY}:/neural-compressor ${IMAGE_NAME}:${IMAGE_TAG} \
        bash -c "cd /neural-compressor/.azure-pipelines/scripts \
        && bash install_nc_full.sh \
        && bash ut/run_ux.sh"
      displayName: 'Install Neural Compressor and run UT'